apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-init-script
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  init.sh: |
    #!/bin/sh
    # Wait for todoapp to be ready
    until curl -sf http://{{ .Release.Name }}:{{ .Values.service.port }}/healthz; do
      echo "Waiting for {{ .Release.Name }} to be ready..."
      sleep 10
    done
    echo =-=-=-=-=-=-=-= Allow anonymous access for pulling =-=-=-=-=-=-=-=
    curl -X POST 'http://{{ .Release.Name }}:{{ .Values.service.port }}/todos' \
      -H 'accept: application/json' -H 'Content-Type: application/json' \
      -d '{"text":"First test todo" }'
    echo "Initialization script completed."