apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-init-script
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  init.sh: |
    #!/bin/sh
    # Wait for todoapp to be ready
    {{- $svcName := default (printf "%s" .Release.Name) .Values.service.name }}
    {{- $svcNS := default .Release.Namespace .Values.service.namespace }}
    {{- $svcPort := int (default 8080 .Values.service.port) }}
    {{- $svcFQDN := printf "%s.%s.svc.cluster.local:%d" $svcName $svcNS $svcPort }}
    until curl -sf http://{{ $svcFQDN }}/healthz; do
      echo "Waiting for {{ .Release.Name }} to be ready..."
      sleep 10
    done
    echo =-=-=-=-=-=-=-= Create first Todo =-=-=-=-=-=-=-=
    curl -X POST 'http://{{ $svcFQDN }}/todos' \
      -H 'accept: application/json' -H 'Content-Type: application/json' \
      -d '{"text":"First test todo" }'
    echo "Initialization script completed."